# This function showcases how one might write a function to be used as an
# RStudio project template. This function will be called when the user invokes
# the New Project wizard using the project template defined in the template file
# at:
#
#   inst/rstudio/templates/project/hello_world.dcf
#
# The function itself just echos its inputs and outputs to a file called INDEX,
# which is then opened by RStudio when the new project is opened.
jon_project_template <- function(path, ...) {

  # ensure path exists
  dir.create(path, recursive = TRUE, showWarnings = FALSE)

  # generate header
  header <- c(
    "# This file was generated by a call to 'ptexamples::jon_project_template()'.",
    "# The following inputs were received:",
    ""
  )

  # collect inputs
  dots <- list(...)
  text <- lapply(seq_along(dots), function(i) {
    key <- names(dots)[[i]]
    val <- dots[[i]]
    paste0(key, ": ", val)
  })

  # collect into single text string
  contents <- paste(
    paste(header, collapse = "\n"),
    paste(text, collapse = "\n"),
    sep = "\n"
  )

  # write to index file
  writeLines(contents, con = file.path(path, "INDEX"))
  writeLines(paste("#", path), con = file.path(path, "README.md"))

  # create directory structure
  dir.create(file.path(path, "R/"))
  writeLines(text = NULL, con = file.path(path, "R/.gitkeep"))
  dir.create(file.path(path, "data"))
  dir.create(file.path(path, "data/raw/"))
  writeLines(text = NULL, con = file.path(path, "data/raw/.gitkeep"))
  dir.create(file.path(path, "data/interim/"))
  writeLines(text = NULL, con = file.path(path, "data/interim/.gitkeep"))
  dir.create(file.path(path, "data/processed/"))
  writeLines(text = NULL, con = file.path(path, "data/processed/.gitkeep"))
  dir.create(file.path(path, "notebooks/"))
  writeLines(text = NULL, con = file.path(path, "notebooks/.gitkeep"))
  dir.create(file.path(path, "references/"))
  writeLines(text = NULL, con = file.path(path, "references/.gitkeep"))


  # create .gitignore file
  gitignore_contents <- paste(
    paste("# RStudio files",".Rproj.user", "", sep = "\n"),
    paste("# History files",".Rhistory", "", sep = "\n"),
    paste("# Session Data files",".RData", "", sep = "\n"),
    sep = "\n"
  )
  writeLines(gitignore_contents, con = file.path(path, ".gitignore"))

}

